// DEV-ONLY. Writes to localStorage only — never to Supabase.
// Production has no fixture notices/resources. See docs/production-seed.md.
// Doc 1.2 seed notices & resources. Local only — no real email sent.

import type { Notice, Resource } from './types';
import { IT_SUPPORT_EMAIL } from './types';

const isoDaysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const SEED_NOTICES: Notice[] = [
  {
    id: 'ntc_welcome',
    title: 'Welcome to AIHQ Internal Hub',
    message:
      'This is your new internal hub for notices, resources, requests, and payslips. Bookmark it and check the Latest Notices section regularly.',
    type: 'GeneralAnnouncement',
    importance: 'Normal',
    audience: { kind: 'Everyone' },
    links: [],
    createdBy: 'stf_admin01',
    createdAt: isoDaysAgo(7),
    publishedAt: isoDaysAgo(7),
    emailRequired: true,
    archived: false,
  },
  {
    id: 'ntc_payroll_window',
    title: 'Claims cutoff: 25th of the month',
    message:
      'Please submit all claims by the 25th to be included in this payroll cycle. Late submissions roll over to next month.',
    type: 'DeadlineReminder',
    importance: 'Important',
    audience: { kind: 'Everyone' },
    links: [],
    createdBy: 'stf_admin01',
    createdAt: isoDaysAgo(3),
    publishedAt: isoDaysAgo(3),
    emailRequired: true,
    archived: false,
  },
  {
    id: 'ntc_policy_update',
    title: 'Updated Leave Policy — please acknowledge',
    message:
      'The leave policy has been updated effective this month. Please review the updated SOP in Resources and acknowledge.',
    type: 'AdminBroadcast',
    importance: 'AcknowledgmentRequired',
    audience: { kind: 'Everyone' },
    links: [{ label: 'View updated policy', url: 'https://www.notion.so/aihq-leave-policy' }],
    createdBy: 'stf_admin01',
    createdAt: isoDaysAgo(1),
    publishedAt: isoDaysAgo(1),
    emailRequired: true,
    archived: false,
  },
];

const iso = new Date().toISOString();

export const SEED_RESOURCES: Resource[] = [
  {
    id: 'res_yt',
    title: 'AIHQ YouTube Training',
    category: 'YouTubeTraining',
    link: 'https://youtube.com/@aihq',
    description: 'Official YouTube training playlists for new and existing staff.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_notion',
    title: 'Notion Knowledge Base',
    category: 'NotionKB',
    link: 'https://www.notion.so/aihq',
    description: 'Internal knowledge base. Access unlocks 1 month after joining.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_chatgpt',
    title: 'ChatGPT / OpenAI',
    category: 'CompanyTools',
    link: 'https://chat.openai.com',
    description: 'Shared workspace access — request from admin if not granted.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_gemini',
    title: 'Gemini',
    category: 'CompanyTools',
    link: 'https://gemini.google.com',
    description: 'Google Gemini access for company use.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_gdrive',
    title: 'Google Drive',
    category: 'CompanyTools',
    link: 'https://drive.google.com',
    description: 'Company Google Drive workspace.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_social',
    title: 'AIHQ Social Media Pages',
    category: 'CompanyTools',
    link: 'https://www.linkedin.com/company/theaihq',
    description: 'Official AIHQ social pages.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_leave_sop',
    title: 'Leave & MC SOP',
    category: 'Policies',
    link: 'https://www.notion.so/aihq-leave-policy',
    description: 'How to apply for leave, MC submission, and approval flow.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_claims_sop',
    title: 'Claims SOP',
    category: 'Policies',
    link: 'https://www.notion.so/aihq-claims',
    description: 'Submission, evidence, and reimbursement timing.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_insurance',
    title: 'Insurance & Benefits',
    category: 'Benefits',
    link: 'https://www.notion.so/aihq-benefits',
    description: 'Insurance coverage, claim contacts, and benefit guides.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_onboarding',
    title: 'AIHQ Ways of Working',
    category: 'OnboardingMaterials',
    link: 'https://www.notion.so/aihq-ways',
    description: 'New starter orientation and team conventions.',
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
    external: true,
  },
  {
    id: 'res_it_support',
    title: 'Email IT Support',
    category: 'ITSupport',
    link: `mailto:${IT_SUPPORT_EMAIL}`,
    description: `For tools, access, or account issues, email ${IT_SUPPORT_EMAIL}.`,
    audience: { kind: 'Everyone' },
    status: 'Active',
    createdAt: iso,
    updatedAt: iso,
  },
];
