// ============================================
// AIHQ Placement System - Mock Database
// Seed data for demo/development
// ============================================

import {
  EmployerCompany,
  EmployerUser,
  PlacementUser,
  RoleOpening,
  CandidateProfile,
  CandidateSubmission,
  LOIRecord,
  SelectionRecord,
  ProgrammeTracker,
  ActivityLog,
  TaskItem,
  TalentRequest,
} from './types';

// ============================================
// COMPANIES
// ============================================

export const mockCompanies: EmployerCompany[] = [
  {
    id: 'company-1',
    name: 'TechVentures Pte Ltd',
    industry: 'Technology',
    size: '100-500',
    website: 'https://techventures.sg',
    address: '1 Marina Boulevard, Singapore 018989',
    contactEmail: 'hr@techventures.sg',
    contactPhone: '+65 6123 4567',
    status: 'ACTIVE',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'company-2',
    name: 'FinanceHub Singapore',
    industry: 'Financial Services',
    size: '500-1000',
    website: 'https://financehub.sg',
    address: '8 Shenton Way, Singapore 068811',
    contactEmail: 'careers@financehub.sg',
    contactPhone: '+65 6234 5678',
    status: 'ACTIVE',
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2024-02-10T09:00:00Z',
  },
  {
    id: 'company-3',
    name: 'GreenEnergy Solutions',
    industry: 'Energy',
    size: '50-100',
    website: 'https://greenenergy.sg',
    address: '10 Pasir Panjang Road, Singapore 117438',
    contactEmail: 'talent@greenenergy.sg',
    contactPhone: '+65 6345 6789',
    status: 'ACTIVE',
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
];

// ============================================
// EMPLOYER USERS
// ============================================

export const mockEmployerUsers: EmployerUser[] = [
  {
    id: 'emp-user-1',
    companyId: 'company-1',
    email: 'alice.tan@techventures.sg',
    name: 'Alice Tan',
    role: 'COMPANY_ADMIN',
    phone: '+65 9123 4567',
    jobTitle: 'HR Director',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'emp-user-2',
    companyId: 'company-1',
    email: 'bob.lee@techventures.sg',
    name: 'Bob Lee',
    role: 'HIRING_MANAGER',
    phone: '+65 9234 5678',
    jobTitle: 'Engineering Manager',
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-01-20T09:00:00Z',
  },
  {
    id: 'emp-user-3',
    companyId: 'company-2',
    email: 'carol.wong@financehub.sg',
    name: 'Carol Wong',
    role: 'COMPANY_ADMIN',
    phone: '+65 9345 6789',
    jobTitle: 'Talent Acquisition Lead',
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2024-02-10T09:00:00Z',
  },
  {
    id: 'emp-user-4',
    companyId: 'company-2',
    email: 'david.lim@financehub.sg',
    name: 'David Lim',
    role: 'HIRING_MANAGER',
    phone: '+65 9456 7890',
    jobTitle: 'VP Operations',
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    id: 'emp-user-5',
    companyId: 'company-3',
    email: 'eve.chen@greenenergy.sg',
    name: 'Eve Chen',
    role: 'COMPANY_ADMIN',
    phone: '+65 9567 8901',
    jobTitle: 'People & Culture Manager',
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
];

// ============================================
// PLACEMENT USERS (includes Ops)
// ============================================

export const mockPlacementUsers: PlacementUser[] = [
  // Employer users mapped
  ...mockEmployerUsers.map((eu) => ({
    id: eu.id,
    email: eu.email,
    name: eu.name,
    role: eu.role as 'COMPANY_ADMIN' | 'HIRING_MANAGER',
    companyId: eu.companyId,
    createdAt: eu.createdAt,
    updatedAt: eu.updatedAt,
  })),
  // Ops users
  {
    id: 'ops-user-1',
    email: 'ops1@aihq.sg',
    name: 'Sarah Ops',
    role: 'AIHQ_OPS',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'ops-user-2',
    email: 'ops2@aihq.sg',
    name: 'Mike Ops',
    role: 'AIHQ_OPS',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
  {
    id: 'admin-user-1',
    email: 'admin@aihq.sg',
    name: 'Admin User',
    role: 'AIHQ_ADMIN',
    createdAt: '2024-01-01T08:00:00Z',
    updatedAt: '2024-01-01T08:00:00Z',
  },
];

// ============================================
// ROLES
// ============================================

export const mockRoles: RoleOpening[] = [
  {
    id: 'role-1',
    companyId: 'company-1',
    companyName: 'TechVentures Pte Ltd',
    title: 'AI Engineer',
    department: 'Engineering',
    description: 'We are looking for an AI Engineer to join our growing team. You will work on cutting-edge machine learning models and deploy them to production.',
    requirements: [
      'Bachelors degree in Computer Science or related field',
      '2+ years experience with Python and ML frameworks',
      'Experience with TensorFlow or PyTorch',
      'Strong understanding of deep learning concepts',
    ],
    niceToHave: [
      'Experience with cloud platforms (AWS/GCP)',
      'Published research in ML/AI',
    ],
    salaryMin: 6000,
    salaryMax: 9000,
    workArrangement: 'HYBRID',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 2,
    status: 'INTERVIEWING',
    createdById: 'emp-user-2',
    createdByName: 'Bob Lee',
    loiStatus: 'VERIFIED',
    loiSignedAt: '2024-11-20T10:00:00Z',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
  },
  {
    id: 'role-2',
    companyId: 'company-1',
    companyName: 'TechVentures Pte Ltd',
    title: 'Full Stack Developer',
    department: 'Engineering',
    description: 'Join our product team to build innovative web applications using modern technologies.',
    requirements: [
      'Experience with React and Node.js',
      'Familiarity with TypeScript',
      'Database design experience',
      'API development skills',
    ],
    salaryMin: 5000,
    salaryMax: 7500,
    workArrangement: 'ONSITE',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 1,
    status: 'OPEN',
    createdById: 'emp-user-2',
    createdByName: 'Bob Lee',
    loiStatus: 'NOT_REQUESTED',
    createdAt: '2024-12-01T09:00:00Z',
    updatedAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'role-3',
    companyId: 'company-2',
    companyName: 'FinanceHub Singapore',
    title: 'Data Analyst',
    department: 'Analytics',
    description: 'Analyze financial data and create insights to drive business decisions.',
    requirements: [
      'Strong SQL skills',
      'Experience with Python or R',
      'Data visualization skills (Tableau/PowerBI)',
      'Financial industry knowledge preferred',
    ],
    salaryMin: 5500,
    salaryMax: 8000,
    workArrangement: 'HYBRID',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 1,
    status: 'SELECTING',
    createdById: 'emp-user-4',
    createdByName: 'David Lim',
    loiStatus: 'VERIFIED',
    loiSignedAt: '2024-11-25T14:00:00Z',
    createdAt: '2024-10-15T10:00:00Z',
    updatedAt: '2024-12-20T11:00:00Z',
  },
  {
    id: 'role-4',
    companyId: 'company-2',
    companyName: 'FinanceHub Singapore',
    title: 'Cybersecurity Specialist',
    department: 'IT Security',
    description: 'Protect our financial systems and ensure compliance with security standards.',
    requirements: [
      'CISSP or equivalent certification',
      '3+ years in cybersecurity',
      'Experience with SIEM tools',
      'Knowledge of financial regulations',
    ],
    salaryMin: 7000,
    salaryMax: 10000,
    workArrangement: 'ONSITE',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 1,
    status: 'OPEN',
    createdById: 'emp-user-3',
    createdByName: 'Carol Wong',
    loiStatus: 'NOT_REQUESTED',
    createdAt: '2024-12-10T08:00:00Z',
    updatedAt: '2024-12-10T08:00:00Z',
  },
  {
    id: 'role-5',
    companyId: 'company-3',
    companyName: 'GreenEnergy Solutions',
    title: 'Sustainability Consultant',
    department: 'Consulting',
    description: 'Help our clients achieve their sustainability goals through data-driven solutions.',
    requirements: [
      'Background in environmental science or engineering',
      'Experience with sustainability reporting',
      'Strong analytical skills',
      'Excellent communication skills',
    ],
    salaryMin: 4500,
    salaryMax: 6500,
    workArrangement: 'HYBRID',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 2,
    status: 'OPEN',
    createdById: 'emp-user-5',
    createdByName: 'Eve Chen',
    loiStatus: 'NOT_REQUESTED',
    createdAt: '2024-12-05T11:00:00Z',
    updatedAt: '2024-12-05T11:00:00Z',
  },
  {
    id: 'role-6',
    companyId: 'company-1',
    companyName: 'TechVentures Pte Ltd',
    title: 'Product Manager',
    department: 'Product',
    description: 'Lead product strategy and work with engineering to deliver amazing products.',
    requirements: [
      '3+ years product management experience',
      'Technical background preferred',
      'Strong stakeholder management',
      'Data-driven decision making',
    ],
    salaryMin: 7000,
    salaryMax: 10000,
    workArrangement: 'HYBRID',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 1,
    status: 'PLACED',
    createdById: 'emp-user-1',
    createdByName: 'Alice Tan',
    loiStatus: 'VERIFIED',
    loiSignedAt: '2024-09-15T10:00:00Z',
    selectedCandidateId: 'candidate-1',
    placedAt: '2024-10-01T09:00:00Z',
    createdAt: '2024-08-01T08:00:00Z',
    updatedAt: '2024-10-01T09:00:00Z',
  },
  {
    id: 'role-7',
    companyId: 'company-3',
    companyName: 'GreenEnergy Solutions',
    title: 'Marketing Coordinator',
    department: 'Marketing',
    description: 'Support marketing campaigns and manage social media presence.',
    requirements: [
      'Degree in Marketing or Communications',
      'Social media management experience',
      'Content creation skills',
      'Basic design skills (Canva/Adobe)',
    ],
    salaryMin: 3500,
    salaryMax: 4500,
    workArrangement: 'ONSITE',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 1,
    status: 'DRAFT',
    createdById: 'emp-user-5',
    createdByName: 'Eve Chen',
    loiStatus: 'NOT_REQUESTED',
    createdAt: '2024-12-20T14:00:00Z',
    updatedAt: '2024-12-20T14:00:00Z',
  },
  {
    id: 'role-8',
    companyId: 'company-2',
    companyName: 'FinanceHub Singapore',
    title: 'Business Analyst',
    department: 'Strategy',
    description: 'Drive business improvements through analysis and process optimization.',
    requirements: [
      'Strong analytical and problem-solving skills',
      'Experience with process mapping',
      'SQL and Excel proficiency',
      'Excellent documentation skills',
    ],
    salaryMin: 5000,
    salaryMax: 7000,
    workArrangement: 'HYBRID',
    employmentType: 'FULL_TIME',
    location: 'Singapore',
    headcount: 1,
    status: 'CLOSED',
    createdById: 'emp-user-4',
    createdByName: 'David Lim',
    loiStatus: 'VERIFIED',
    closedAt: '2024-11-30T17:00:00Z',
    closedReason: 'Position filled through internal transfer',
    createdAt: '2024-09-01T08:00:00Z',
    updatedAt: '2024-11-30T17:00:00Z',
  },
];

// ============================================
// CANDIDATES
// ============================================

export const mockCandidates: CandidateProfile[] = [
  {
    id: 'candidate-1',
    fullName: 'John Ng Wei Ming',
    email: 'john.ng@email.com',
    phone: '+65 8111 2222',
    nric: 'S9012345A',
    dateOfBirth: '1990-05-15',
    displayName: 'Candidate JN',
    currentRole: 'Senior Developer',
    yearsExperience: 5,
    skills: ['Python', 'JavaScript', 'React', 'Node.js', 'PostgreSQL', 'AWS'],
    education: 'BSc Computer Science, NUS',
    certifications: ['AWS Solutions Architect'],
    summary: 'Experienced full-stack developer with strong background in web applications and cloud technologies.',
    availability: 'TWO_WEEKS',
    expectedSalary: 8000,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['HYBRID', 'REMOTE'],
    source: 'Career Fair 2024',
    createdAt: '2024-06-15T10:00:00Z',
    updatedAt: '2024-06-15T10:00:00Z',
  },
  {
    id: 'candidate-2',
    fullName: 'Sarah Lim Hui Ling',
    email: 'sarah.lim@email.com',
    phone: '+65 8222 3333',
    nric: 'S9123456B',
    dateOfBirth: '1991-08-22',
    displayName: 'Candidate SL',
    currentRole: 'Data Scientist',
    yearsExperience: 4,
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Tableau', 'Statistics'],
    education: 'MSc Data Science, NTU',
    certifications: ['Google Data Analytics'],
    summary: 'Data scientist with expertise in machine learning and statistical analysis. Passionate about deriving insights from data.',
    availability: 'IMMEDIATE',
    expectedSalary: 7500,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['HYBRID'],
    source: 'AI Training Programme',
    programmeId: 'prog-ai-2024',
    programmeName: 'AI for Business Programme 2024',
    createdAt: '2024-07-01T09:00:00Z',
    updatedAt: '2024-07-01T09:00:00Z',
  },
  {
    id: 'candidate-3',
    fullName: 'Michael Tan Jun Wei',
    email: 'michael.tan@email.com',
    phone: '+65 8333 4444',
    nric: 'S8912345C',
    dateOfBirth: '1989-03-10',
    displayName: 'Candidate MT',
    currentRole: 'Cybersecurity Analyst',
    yearsExperience: 6,
    skills: ['Network Security', 'SIEM', 'Penetration Testing', 'ISO 27001', 'Python'],
    education: 'BSc Information Security, SMU',
    certifications: ['CISSP', 'CEH'],
    summary: 'Certified cybersecurity professional with experience in financial services. Strong background in threat detection and incident response.',
    availability: 'ONE_MONTH',
    expectedSalary: 9000,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['ONSITE', 'HYBRID'],
    source: 'Referral',
    createdAt: '2024-08-15T11:00:00Z',
    updatedAt: '2024-08-15T11:00:00Z',
  },
  {
    id: 'candidate-4',
    fullName: 'Emily Wong Mei Ling',
    email: 'emily.wong@email.com',
    phone: '+65 8444 5555',
    nric: 'S9234567D',
    dateOfBirth: '1992-11-28',
    displayName: 'Candidate EW',
    currentRole: 'Junior Developer',
    yearsExperience: 2,
    skills: ['JavaScript', 'React', 'TypeScript', 'Node.js', 'MongoDB'],
    education: 'BSc Computer Science, SUTD',
    summary: 'Enthusiastic developer eager to grow in full-stack development. Quick learner with strong fundamentals.',
    availability: 'IMMEDIATE',
    expectedSalary: 5500,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['ONSITE', 'HYBRID'],
    source: 'Career Fair 2024',
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'candidate-5',
    fullName: 'David Koh Cheng Wei',
    email: 'david.koh@email.com',
    phone: '+65 8555 6666',
    nric: 'S8823456E',
    dateOfBirth: '1988-07-05',
    displayName: 'Candidate DK',
    currentRole: 'Product Manager',
    yearsExperience: 7,
    skills: ['Product Strategy', 'Agile', 'User Research', 'SQL', 'Jira', 'Data Analysis'],
    education: 'MBA, INSEAD',
    summary: 'Seasoned product manager with track record of launching successful B2B products. Strong technical background.',
    availability: 'TWO_WEEKS',
    expectedSalary: 10000,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['HYBRID', 'REMOTE'],
    source: 'LinkedIn',
    createdAt: '2024-07-20T08:00:00Z',
    updatedAt: '2024-07-20T08:00:00Z',
  },
  {
    id: 'candidate-6',
    fullName: 'Rachel Teo Shu Min',
    email: 'rachel.teo@email.com',
    phone: '+65 8666 7777',
    nric: 'S9345678F',
    dateOfBirth: '1993-02-14',
    displayName: 'Candidate RT',
    currentRole: 'Business Analyst',
    yearsExperience: 3,
    skills: ['SQL', 'Excel', 'Tableau', 'Process Mapping', 'Requirements Gathering'],
    education: 'BSc Business Analytics, NUS',
    summary: 'Detail-oriented analyst with experience in financial services. Strong communication and stakeholder management skills.',
    availability: 'IMMEDIATE',
    expectedSalary: 6000,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['HYBRID'],
    source: 'Job Portal',
    createdAt: '2024-10-05T09:00:00Z',
    updatedAt: '2024-10-05T09:00:00Z',
  },
  {
    id: 'candidate-7',
    fullName: 'Kevin Lee Jia Hao',
    email: 'kevin.lee@email.com',
    phone: '+65 8777 8888',
    nric: 'S9056789G',
    dateOfBirth: '1990-09-20',
    displayName: 'Candidate KL',
    currentRole: 'ML Engineer',
    yearsExperience: 4,
    skills: ['Python', 'PyTorch', 'MLOps', 'Docker', 'Kubernetes', 'AWS'],
    education: 'MSc Artificial Intelligence, NUS',
    summary: 'ML engineer specializing in deploying production ML systems. Experience with end-to-end ML pipelines.',
    availability: 'TWO_WEEKS',
    expectedSalary: 8500,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['HYBRID', 'REMOTE'],
    source: 'AI Training Programme',
    programmeId: 'prog-ai-2024',
    programmeName: 'AI for Business Programme 2024',
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'candidate-8',
    fullName: 'Amanda Chua Li Ting',
    email: 'amanda.chua@email.com',
    phone: '+65 8888 9999',
    nric: 'S9167890H',
    dateOfBirth: '1991-12-03',
    displayName: 'Candidate AC',
    currentRole: 'Environmental Consultant',
    yearsExperience: 4,
    skills: ['Sustainability Reporting', 'ESG', 'Data Analysis', 'Project Management'],
    education: 'MSc Environmental Management, NUS',
    summary: 'Environmental consultant with experience in corporate sustainability. Passionate about green initiatives.',
    availability: 'IMMEDIATE',
    expectedSalary: 5500,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['HYBRID', 'ONSITE'],
    source: 'Career Fair 2024',
    createdAt: '2024-11-01T11:00:00Z',
    updatedAt: '2024-11-01T11:00:00Z',
  },
  {
    id: 'candidate-9',
    fullName: 'Jason Ong Wei Jie',
    email: 'jason.ong@email.com',
    phone: '+65 8999 0000',
    nric: 'S9278901I',
    dateOfBirth: '1992-04-18',
    displayName: 'Candidate JO',
    currentRole: 'Software Engineer',
    yearsExperience: 3,
    skills: ['Java', 'Spring Boot', 'React', 'PostgreSQL', 'Docker', 'CI/CD'],
    education: 'BSc Computer Engineering, NTU',
    summary: 'Full-stack developer with strong backend focus. Experience in building scalable microservices.',
    availability: 'ONE_MONTH',
    expectedSalary: 6500,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['ONSITE', 'HYBRID'],
    source: 'Job Portal',
    createdAt: '2024-09-15T08:00:00Z',
    updatedAt: '2024-09-15T08:00:00Z',
  },
  {
    id: 'candidate-10',
    fullName: 'Michelle Goh Xin Yi',
    email: 'michelle.goh@email.com',
    phone: '+65 9000 1111',
    nric: 'S9389012J',
    dateOfBirth: '1993-06-25',
    displayName: 'Candidate MG',
    currentRole: 'Data Analyst',
    yearsExperience: 2,
    skills: ['SQL', 'Python', 'Tableau', 'Excel', 'Statistics'],
    education: 'BSc Statistics, NUS',
    summary: 'Analytical thinker with strong foundation in statistics. Eager to transition into data science.',
    availability: 'IMMEDIATE',
    expectedSalary: 5000,
    preferredLocations: ['Singapore'],
    preferredWorkArrangements: ['HYBRID'],
    source: 'Referral',
    createdAt: '2024-10-20T10:00:00Z',
    updatedAt: '2024-10-20T10:00:00Z',
  },
];

// ============================================
// SUBMISSIONS
// ============================================

export const mockSubmissions: CandidateSubmission[] = [
  // Role 1 (AI Engineer) - INTERVIEWING stage
  {
    id: 'sub-1',
    roleId: 'role-1',
    candidateId: 'candidate-2',
    roleName: 'AI Engineer',
    companyName: 'TechVentures Pte Ltd',
    candidateDisplayName: 'Candidate SL',
    stage: 'INTERVIEWED',
    stageHistory: [
      { from: 'SUBMITTED', to: 'SHORTLISTED', changedAt: '2024-11-22T10:00:00Z', changedById: 'emp-user-2', changedByName: 'Bob Lee' },
      { from: 'SHORTLISTED', to: 'INTERVIEW_REQUESTED', changedAt: '2024-11-25T11:00:00Z', changedById: 'emp-user-2', changedByName: 'Bob Lee' },
      { from: 'INTERVIEW_REQUESTED', to: 'INTERVIEW_SCHEDULED', changedAt: '2024-11-26T09:00:00Z', changedById: 'ops-user-1', changedByName: 'Sarah Ops' },
      { from: 'INTERVIEW_SCHEDULED', to: 'INTERVIEWED', changedAt: '2024-12-05T16:00:00Z', changedById: 'emp-user-2', changedByName: 'Bob Lee' },
    ],
    employerRating: 4,
    employerNotes: 'Strong ML background, good communication skills.',
    interviewScheduledAt: '2024-12-05T14:00:00Z',
    interviewNotes: 'Candidate demonstrated deep understanding of ML concepts. Cultural fit looks good.',
    interviewerName: 'Bob Lee',
    submittedById: 'ops-user-1',
    submittedByName: 'Sarah Ops',
    createdAt: '2024-11-20T10:00:00Z',
    updatedAt: '2024-12-05T16:00:00Z',
  },
  {
    id: 'sub-2',
    roleId: 'role-1',
    candidateId: 'candidate-7',
    roleName: 'AI Engineer',
    companyName: 'TechVentures Pte Ltd',
    candidateDisplayName: 'Candidate KL',
    stage: 'INTERVIEW_SCHEDULED',
    stageHistory: [
      { from: 'SUBMITTED', to: 'SHORTLISTED', changedAt: '2024-11-22T10:30:00Z', changedById: 'emp-user-2', changedByName: 'Bob Lee' },
      { from: 'SHORTLISTED', to: 'INTERVIEW_REQUESTED', changedAt: '2024-11-28T14:00:00Z', changedById: 'emp-user-2', changedByName: 'Bob Lee' },
      { from: 'INTERVIEW_REQUESTED', to: 'INTERVIEW_SCHEDULED', changedAt: '2024-12-01T09:00:00Z', changedById: 'ops-user-1', changedByName: 'Sarah Ops' },
    ],
    interviewScheduledAt: '2024-12-28T10:00:00Z',
    submittedById: 'ops-user-1',
    submittedByName: 'Sarah Ops',
    createdAt: '2024-11-20T11:00:00Z',
    updatedAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'sub-3',
    roleId: 'role-1',
    candidateId: 'candidate-4',
    roleName: 'AI Engineer',
    companyName: 'TechVentures Pte Ltd',
    candidateDisplayName: 'Candidate EW',
    stage: 'SUBMITTED',
    stageHistory: [],
    submittedById: 'ops-user-2',
    submittedByName: 'Mike Ops',
    createdAt: '2024-12-15T10:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
  },
  // Role 3 (Data Analyst) - SELECTING stage
  {
    id: 'sub-4',
    roleId: 'role-3',
    candidateId: 'candidate-6',
    roleName: 'Data Analyst',
    companyName: 'FinanceHub Singapore',
    candidateDisplayName: 'Candidate RT',
    stage: 'OFFERED',
    stageHistory: [
      { from: 'SUBMITTED', to: 'SHORTLISTED', changedAt: '2024-11-01T10:00:00Z', changedById: 'emp-user-4', changedByName: 'David Lim' },
      { from: 'SHORTLISTED', to: 'INTERVIEW_REQUESTED', changedAt: '2024-11-05T11:00:00Z', changedById: 'emp-user-4', changedByName: 'David Lim' },
      { from: 'INTERVIEW_REQUESTED', to: 'INTERVIEW_SCHEDULED', changedAt: '2024-11-06T09:00:00Z', changedById: 'ops-user-1', changedByName: 'Sarah Ops' },
      { from: 'INTERVIEW_SCHEDULED', to: 'INTERVIEWED', changedAt: '2024-11-15T16:00:00Z', changedById: 'emp-user-4', changedByName: 'David Lim' },
      { from: 'INTERVIEWED', to: 'OFFERED', changedAt: '2024-12-18T10:00:00Z', changedById: 'emp-user-3', changedByName: 'Carol Wong' },
    ],
    employerRating: 5,
    employerNotes: 'Excellent fit for the role. Strong analytical skills.',
    interviewScheduledAt: '2024-11-15T14:00:00Z',
    interviewNotes: 'Very impressive candidate. Recommended for offer.',
    interviewerName: 'David Lim',
    submittedById: 'ops-user-1',
    submittedByName: 'Sarah Ops',
    createdAt: '2024-10-25T09:00:00Z',
    updatedAt: '2024-12-18T10:00:00Z',
  },
  {
    id: 'sub-5',
    roleId: 'role-3',
    candidateId: 'candidate-10',
    roleName: 'Data Analyst',
    companyName: 'FinanceHub Singapore',
    candidateDisplayName: 'Candidate MG',
    stage: 'INTERVIEWED',
    stageHistory: [
      { from: 'SUBMITTED', to: 'SHORTLISTED', changedAt: '2024-11-02T11:00:00Z', changedById: 'emp-user-4', changedByName: 'David Lim' },
      { from: 'SHORTLISTED', to: 'INTERVIEW_REQUESTED', changedAt: '2024-11-08T10:00:00Z', changedById: 'emp-user-4', changedByName: 'David Lim' },
      { from: 'INTERVIEW_REQUESTED', to: 'INTERVIEW_SCHEDULED', changedAt: '2024-11-09T09:00:00Z', changedById: 'ops-user-2', changedByName: 'Mike Ops' },
      { from: 'INTERVIEW_SCHEDULED', to: 'INTERVIEWED', changedAt: '2024-11-20T15:00:00Z', changedById: 'emp-user-4', changedByName: 'David Lim' },
    ],
    employerRating: 4,
    employerNotes: 'Good potential, needs mentoring.',
    interviewScheduledAt: '2024-11-20T14:00:00Z',
    interviewNotes: 'Solid foundation, could grow into the role.',
    interviewerName: 'David Lim',
    submittedById: 'ops-user-2',
    submittedByName: 'Mike Ops',
    createdAt: '2024-10-28T10:00:00Z',
    updatedAt: '2024-11-20T15:00:00Z',
  },
  // Role 5 (Sustainability Consultant) - OPEN
  {
    id: 'sub-6',
    roleId: 'role-5',
    candidateId: 'candidate-8',
    roleName: 'Sustainability Consultant',
    companyName: 'GreenEnergy Solutions',
    candidateDisplayName: 'Candidate AC',
    stage: 'SUBMITTED',
    stageHistory: [],
    submittedById: 'ops-user-1',
    submittedByName: 'Sarah Ops',
    createdAt: '2024-12-10T11:00:00Z',
    updatedAt: '2024-12-10T11:00:00Z',
  },
  // Placed role submission
  {
    id: 'sub-7',
    roleId: 'role-6',
    candidateId: 'candidate-5',
    roleName: 'Product Manager',
    companyName: 'TechVentures Pte Ltd',
    candidateDisplayName: 'Candidate DK',
    stage: 'SELECTED',
    stageHistory: [
      { from: 'SUBMITTED', to: 'SHORTLISTED', changedAt: '2024-08-15T10:00:00Z', changedById: 'emp-user-1', changedByName: 'Alice Tan' },
      { from: 'SHORTLISTED', to: 'INTERVIEW_REQUESTED', changedAt: '2024-08-20T11:00:00Z', changedById: 'emp-user-1', changedByName: 'Alice Tan' },
      { from: 'INTERVIEW_REQUESTED', to: 'INTERVIEW_SCHEDULED', changedAt: '2024-08-21T09:00:00Z', changedById: 'ops-user-1', changedByName: 'Sarah Ops' },
      { from: 'INTERVIEW_SCHEDULED', to: 'INTERVIEWED', changedAt: '2024-09-01T16:00:00Z', changedById: 'emp-user-1', changedByName: 'Alice Tan' },
      { from: 'INTERVIEWED', to: 'OFFERED', changedAt: '2024-09-10T10:00:00Z', changedById: 'emp-user-1', changedByName: 'Alice Tan' },
      { from: 'OFFERED', to: 'SELECTED', changedAt: '2024-09-20T14:00:00Z', changedById: 'emp-user-1', changedByName: 'Alice Tan' },
    ],
    employerRating: 5,
    employerNotes: 'Exceptional candidate. Perfect fit.',
    interviewScheduledAt: '2024-09-01T14:00:00Z',
    interviewNotes: 'Outstanding interview. Strong leadership potential.',
    interviewerName: 'Alice Tan',
    selectedAt: '2024-09-20T14:00:00Z',
    offerDetails: 'Offered $9,500/month with stock options',
    submittedById: 'ops-user-1',
    submittedByName: 'Sarah Ops',
    createdAt: '2024-08-10T09:00:00Z',
    updatedAt: '2024-09-20T14:00:00Z',
  },
];

// ============================================
// LOI RECORDS
// ============================================

export const mockLOIRecords: LOIRecord[] = [
  {
    id: 'loi-1',
    roleId: 'role-1',
    companyId: 'company-1',
    status: 'VERIFIED',
    templateDownloadedAt: '2024-11-18T10:00:00Z',
    templateDownloadedById: 'emp-user-1',
    signedDocumentUrl: '/documents/loi-role-1-signed.pdf',
    uploadedAt: '2024-11-19T14:00:00Z',
    uploadedById: 'emp-user-1',
    uploadedByName: 'Alice Tan',
    verifiedAt: '2024-11-20T10:00:00Z',
    verifiedById: 'ops-user-1',
    verifiedByName: 'Sarah Ops',
    verificationNotes: 'All details verified. LOI approved.',
    createdAt: '2024-11-18T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
  },
  {
    id: 'loi-2',
    roleId: 'role-3',
    companyId: 'company-2',
    status: 'VERIFIED',
    templateDownloadedAt: '2024-11-23T09:00:00Z',
    templateDownloadedById: 'emp-user-3',
    signedDocumentUrl: '/documents/loi-role-3-signed.pdf',
    uploadedAt: '2024-11-24T11:00:00Z',
    uploadedById: 'emp-user-3',
    uploadedByName: 'Carol Wong',
    verifiedAt: '2024-11-25T14:00:00Z',
    verifiedById: 'ops-user-1',
    verifiedByName: 'Sarah Ops',
    createdAt: '2024-11-23T09:00:00Z',
    updatedAt: '2024-11-25T14:00:00Z',
  },
  {
    id: 'loi-3',
    roleId: 'role-6',
    companyId: 'company-1',
    status: 'VERIFIED',
    templateDownloadedAt: '2024-09-12T10:00:00Z',
    templateDownloadedById: 'emp-user-1',
    signedDocumentUrl: '/documents/loi-role-6-signed.pdf',
    uploadedAt: '2024-09-13T15:00:00Z',
    uploadedById: 'emp-user-1',
    uploadedByName: 'Alice Tan',
    verifiedAt: '2024-09-15T10:00:00Z',
    verifiedById: 'ops-user-1',
    verifiedByName: 'Sarah Ops',
    createdAt: '2024-09-12T10:00:00Z',
    updatedAt: '2024-09-15T10:00:00Z',
  },
];

// ============================================
// SELECTION RECORDS
// ============================================

export const mockSelectionRecords: SelectionRecord[] = [
  {
    id: 'sel-1',
    roleId: 'role-6',
    submissionId: 'sub-7',
    candidateId: 'candidate-5',
    companyId: 'company-1',
    roleName: 'Product Manager',
    companyName: 'TechVentures Pte Ltd',
    candidateName: 'David Koh',
    selectedAt: '2024-09-20T14:00:00Z',
    selectedById: 'emp-user-1',
    selectedByName: 'Alice Tan',
    offeredSalary: 9500,
    startDate: '2024-10-01',
    offerNotes: 'Including stock options and performance bonus',
    placementConfirmed: true,
    placementConfirmedAt: '2024-10-01T09:00:00Z',
    createdAt: '2024-09-20T14:00:00Z',
    updatedAt: '2024-10-01T09:00:00Z',
  },
];

// ============================================
// PROGRAMME TRACKERS
// ============================================

export const mockProgrammeTrackers: ProgrammeTracker[] = [
  {
    id: 'prog-tracker-1',
    selectionId: 'sel-1',
    roleId: 'role-6',
    candidateId: 'candidate-5',
    companyId: 'company-1',
    programmeName: 'Leadership Onboarding Programme',
    programmeDescription: '3-month structured onboarding for senior hires',
    startDate: '2024-10-01',
    endDate: '2024-12-31',
    trainingStatus: 'IN_PROGRESS',
    completionPercentage: 75,
    milestones: [
      { id: 'ms-1', name: 'Week 1 Orientation', completedAt: '2024-10-07T17:00:00Z' },
      { id: 'ms-2', name: 'Department Introductions', completedAt: '2024-10-14T17:00:00Z' },
      { id: 'ms-3', name: 'Product Deep Dive', completedAt: '2024-10-28T17:00:00Z' },
      { id: 'ms-4', name: 'First Project Assignment', completedAt: '2024-11-15T17:00:00Z' },
      { id: 'ms-5', name: 'Mid-Programme Review', completedAt: '2024-11-30T17:00:00Z' },
      { id: 'ms-6', name: 'Leadership Workshop', dueDate: '2024-12-15' },
      { id: 'ms-7', name: 'Final Assessment', dueDate: '2024-12-31' },
    ],
    grantApplied: true,
    grantStatus: 'APPROVED',
    grantAmount: 5000,
    grantNotes: 'Career Conversion Programme grant approved',
    createdAt: '2024-10-01T09:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
  },
];

// ============================================
// ACTIVITY LOGS
// ============================================

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'act-1',
    type: 'CANDIDATE_SUBMITTED',
    roleId: 'role-1',
    candidateId: 'candidate-2',
    submissionId: 'sub-1',
    companyId: 'company-1',
    actorId: 'ops-user-1',
    actorName: 'Sarah Ops',
    actorRole: 'AIHQ_OPS',
    title: 'Candidate submitted to AI Engineer role',
    description: 'Candidate SL submitted to TechVentures for AI Engineer position',
    createdAt: '2024-11-20T10:00:00Z',
  },
  {
    id: 'act-2',
    type: 'LOI_VERIFIED',
    roleId: 'role-1',
    companyId: 'company-1',
    actorId: 'ops-user-1',
    actorName: 'Sarah Ops',
    actorRole: 'AIHQ_OPS',
    title: 'LOI verified for AI Engineer role',
    description: 'Letter of Intent verified and approved',
    createdAt: '2024-11-20T10:00:00Z',
  },
  {
    id: 'act-3',
    type: 'CANDIDATE_SHORTLISTED',
    roleId: 'role-1',
    candidateId: 'candidate-2',
    submissionId: 'sub-1',
    companyId: 'company-1',
    actorId: 'emp-user-2',
    actorName: 'Bob Lee',
    actorRole: 'HIRING_MANAGER',
    title: 'Candidate shortlisted',
    description: 'Candidate SL moved to shortlist for AI Engineer role',
    createdAt: '2024-11-22T10:00:00Z',
  },
  {
    id: 'act-4',
    type: 'INTERVIEW_SCHEDULED',
    roleId: 'role-1',
    candidateId: 'candidate-2',
    submissionId: 'sub-1',
    companyId: 'company-1',
    actorId: 'ops-user-1',
    actorName: 'Sarah Ops',
    actorRole: 'AIHQ_OPS',
    title: 'Interview scheduled',
    description: 'Interview scheduled for Dec 5, 2024 at 2:00 PM',
    createdAt: '2024-11-26T09:00:00Z',
  },
  {
    id: 'act-5',
    type: 'PLACEMENT_CONFIRMED',
    roleId: 'role-6',
    candidateId: 'candidate-5',
    submissionId: 'sub-7',
    companyId: 'company-1',
    actorId: 'ops-user-1',
    actorName: 'Sarah Ops',
    actorRole: 'AIHQ_OPS',
    title: 'Placement confirmed',
    description: 'David Koh started as Product Manager at TechVentures',
    createdAt: '2024-10-01T09:00:00Z',
  },
];

// ============================================
// TASKS
// ============================================

export const mockTasks: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Schedule interview for Candidate KL',
    description: 'TechVentures requested interview for AI Engineer role',
    roleId: 'role-1',
    candidateId: 'candidate-7',
    submissionId: 'sub-2',
    companyId: 'company-1',
    assignedToId: 'ops-user-1',
    assignedToName: 'Sarah Ops',
    createdById: 'ops-user-1',
    createdByName: 'Sarah Ops',
    priority: 'HIGH',
    status: 'COMPLETED',
    dueDate: '2024-12-02',
    completedAt: '2024-12-01T09:00:00Z',
    createdAt: '2024-11-28T14:00:00Z',
    updatedAt: '2024-12-01T09:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Review LOI for GreenEnergy Sustainability role',
    description: 'Awaiting LOI upload from employer',
    roleId: 'role-5',
    companyId: 'company-3',
    assignedToId: 'ops-user-2',
    assignedToName: 'Mike Ops',
    createdById: 'ops-user-1',
    createdByName: 'Sarah Ops',
    priority: 'MEDIUM',
    status: 'TODO',
    dueDate: '2024-12-30',
    createdAt: '2024-12-10T11:00:00Z',
    updatedAt: '2024-12-10T11:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Follow up on Data Analyst offer',
    description: 'Candidate RT received offer, awaiting acceptance',
    roleId: 'role-3',
    candidateId: 'candidate-6',
    submissionId: 'sub-4',
    companyId: 'company-2',
    assignedToId: 'ops-user-1',
    assignedToName: 'Sarah Ops',
    createdById: 'ops-user-1',
    createdByName: 'Sarah Ops',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    dueDate: '2024-12-25',
    createdAt: '2024-12-18T10:00:00Z',
    updatedAt: '2024-12-20T14:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Source candidates for Cybersecurity role',
    description: 'FinanceHub looking for Cybersecurity Specialist - need more candidates',
    roleId: 'role-4',
    companyId: 'company-2',
    assignedToId: 'ops-user-2',
    assignedToName: 'Mike Ops',
    createdById: 'ops-user-1',
    createdByName: 'Sarah Ops',
    priority: 'MEDIUM',
    status: 'TODO',
    dueDate: '2025-01-10',
    createdAt: '2024-12-15T09:00:00Z',
    updatedAt: '2024-12-15T09:00:00Z',
  },
];

// ============================================
// TALENT REQUESTS
// ============================================

export const mockTalentRequests: TalentRequest[] = [
  {
    id: 'req-1',
    companyName: 'StartupXYZ',
    contactName: 'Jane Doe',
    contactEmail: 'jane@startupxyz.com',
    contactPhone: '+65 9111 2222',
    roleTitle: 'Backend Developer',
    roleDescription: 'Looking for a backend developer with Node.js experience',
    headcount: 2,
    urgency: 'ONE_MONTH',
    notes: 'Prefer candidates with fintech background',
    status: 'NEW',
    createdAt: '2024-12-20T10:00:00Z',
    updatedAt: '2024-12-20T10:00:00Z',
  },
  {
    id: 'req-2',
    companyName: 'HealthTech Co',
    contactName: 'Dr. Smith',
    contactEmail: 'smith@healthtech.sg',
    roleTitle: 'Data Engineer',
    roleDescription: 'Need data engineer for healthcare analytics platform',
    headcount: 1,
    urgency: 'THREE_MONTHS',
    status: 'CONTACTED',
    createdAt: '2024-12-15T11:00:00Z',
    updatedAt: '2024-12-18T09:00:00Z',
  },
];

// ============================================
// INITIALIZE FUNCTION
// ============================================

const STORAGE_PREFIX = 'placement_';

export function initializeMockData(): void {
  const isInitialized = localStorage.getItem(`${STORAGE_PREFIX}initialized`);
  
  if (!isInitialized) {
    localStorage.setItem(`${STORAGE_PREFIX}companies`, JSON.stringify(mockCompanies));
    localStorage.setItem(`${STORAGE_PREFIX}employerUsers`, JSON.stringify(mockEmployerUsers));
    localStorage.setItem(`${STORAGE_PREFIX}users`, JSON.stringify(mockPlacementUsers));
    localStorage.setItem(`${STORAGE_PREFIX}roles`, JSON.stringify(mockRoles));
    localStorage.setItem(`${STORAGE_PREFIX}candidates`, JSON.stringify(mockCandidates));
    localStorage.setItem(`${STORAGE_PREFIX}submissions`, JSON.stringify(mockSubmissions));
    localStorage.setItem(`${STORAGE_PREFIX}loiRecords`, JSON.stringify(mockLOIRecords));
    localStorage.setItem(`${STORAGE_PREFIX}selectionRecords`, JSON.stringify(mockSelectionRecords));
    localStorage.setItem(`${STORAGE_PREFIX}programmeTrackers`, JSON.stringify(mockProgrammeTrackers));
    localStorage.setItem(`${STORAGE_PREFIX}activityLogs`, JSON.stringify(mockActivityLogs));
    localStorage.setItem(`${STORAGE_PREFIX}tasks`, JSON.stringify(mockTasks));
    localStorage.setItem(`${STORAGE_PREFIX}talentRequests`, JSON.stringify(mockTalentRequests));
    localStorage.setItem(`${STORAGE_PREFIX}initialized`, 'true');
    
    console.log('Placement mock data initialized');
  }
}

export function resetMockData(): void {
  const keys = Object.keys(localStorage).filter(key => key.startsWith(STORAGE_PREFIX));
  keys.forEach(key => localStorage.removeItem(key));
  initializeMockData();
  console.log('Placement mock data reset');
}
